services:
  db:
    image: postgres:16.1
    container_name: shareit_db
    ports:
      - "55432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=shareitdb
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass123
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10